services:
  - type: web
    name: presentation-generator
    env: node
    buildCommand: npm install && npm run build
    startCommand: node dist/app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: FORM_PASSWORD
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: SENDGRID_VERIFIED_EMAIL
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: session-store
          property: connectionString

  - type: redis
    name: session-store
    ipAllowList: []
