services:
  - type: web
    name: presentation-generator
    env: node
    buildCommand: |
      curl -LO https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb &&
      apt-get update &&
      apt-get install -y ./google-chrome-stable_current_amd64.deb &&
      npm install &&
      npm run build
    startCommand: node dist/app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: FORM_PASSWORD
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: SENDGRID_VERIFIED_EMAIL
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: session-store
          property: connectionString
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true

  - type: redis
    name: session-store
    ipAllowList: []
